---
title: "Digitales Begleitmaterial zu Hartmann (2018)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Dieses Begleitmaterial soll Ihnen Handwerkszeug vermitteln, das Sie benötigen, um historische Sprachwissenschaft zu betreiben oder das sich zumindest für bestimmte Forschungsfragen und -projekte als hilfreich erweisen kann. Wie im Buch selbst wird der Schwerpunkt auch hier auf der historischen Korpuslinguistik liegen, wobei es vor allem darum gehen wird, an konkreten Beispielen die Arbeit mit existierenden Korpora des Deutschen kennenzulernen und einzuüben.

Ebenso wenig wie das Buch kann das Begleitmaterial jedoch eine erschöpfende Einführung in die Korpuslinguistik bieten; hierfür verweise ich auf die einschlägige Literatur. Der Schwerpunkt liegt vielmehr darauf, die spezifischen Herausforderungen in der Arbeit mit historischen Korpora kennenzulernen und außerdem ganz praktische Zugänge zur Arbeit mit (Korpus-)Daten zu finden. Letzteres setzt Kenntnisse im EDV-Bereich voraus, über die viele Germanistinnen und Germanisten erfahrungsgemäß nicht verfügen und die ich zumindest in Grundzügen zu vermitteln versuche. (Disclaimer: Damit möchte ich nicht behaupten, selbst ein wirklicher Experte im Bereich Informatik oder Computerlinguistik zu sein. Für vieles, was ich im Folgenden vermittle, mag es bessere und elegantere Lösungen geben – für Anregungen bin ich immer dankbar!)

Im Folgenden finden Sie eine kurze Übersicht über die einzelnen Bestandteile des Begleitmaterials. Wer bereits weiß, was ein csv-Sheet ist und wie man es in Tabellenkalkulationsprogrammen öffnet, wie man versteckte Dateien und Dateinamenerweiterungen einblendet und was der Unterschied zwischen UTF-8 und ANSI ist, kann das erste Dokument getrost überspringen. Allen anderen sei es ans Herz gelegt, da es hilft, viele vermeidbare Fehler zu umgehen und wertvolle Zeit zu sparen!
In Zukunft wird das Begleitmaterial eventuell noch um weitere Tutorials ergänzt, und die bestehenden werden laufend aktualisiert (zumindest ist das mein Plan – deshalb werden sie ja online veröffentlicht und nicht in Buchform).Wenn Sie Fragen, Kritik oder Ergänzungswünsche haben, schreiben Sie mir gern: stefan1.hartmann[at]uni-bamberg.de.

# Schnelleinstieg: Einfache Korpusanalysen
Ergänzend zu den unten aufgelisteten ausführlichen Tutorials finden Sie <a href="https://empirical-linguistics.github.io/korpus-schnelleinstieg/" target="_blank">hier</a> einen Schnelleinstieg in einfache Korpusanalysen am Beispiel der über <a href="https://www.dwds.de/" target="_blank">DWDS</a> verfügbaren Korpora.

# Vom Korpus zur Konkordanz
1.	<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/01-Grundlegendes.pdf" target="_blank">Grundlegendes: Software, Datenstrukturen, Encoding und das geheime Leben meines Computers</a>
2.	<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/02-Arbeitsschritte.pdf" target="_blank">Arbeitsschritte: Vom Korpus zur Konkordanz zur Analyse</a>
3.	<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/03-ANNIS.pdf" target="_blank">Tutorial: ANNIS (Referenzkorpora Altdeutsch, Mittelhochdeutsch, ...)</a>
4.	<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/04-CosmasII_Tutorial.pdf">Tutorial: COSMAS II (Deutsches Referenzkorpus)</a>
5.	<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/05-FnhdC.pdf" target="_blank">Tutorial: Bonner Frühneuhochdeutschkorpus (altes Interface)</a> (R-Skript im Ordner <a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/begleitmaterial/FnhdC" target="_blank">FnhdC</a> auf GitHub)

# Von der Konkordanz zur Analyse
6.	<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/06-Tabellen%20und%20Grafiken%20mit%20Excel%20und%20Calc.pdf" target="_blank">Tutorial: Tabellen und Grafiken mit Excel und Calc</a> (Material dazu im Ordner <a href="https://github.com/hartmast/sprachgeschichte/tree/master/begleitmaterial/Excel_Einstieg" target="_blank">Excel_Einstieg</a> auf GitHub)
7.	<https://hartmast.github.io/sprachgeschichte/begleitmaterial/07-Schnelleinstieg%20in%20R.pdf" target="_blank"> Tutorial: Schnelleinstieg in R</a> (Material dazu im Ordner <a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/R_Einstieg" target="_blank">R_Einstieg</a> auf GitHub)
8.	<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/08-concordances.pdf" target="_blank">Tutorial: R-Paket „concordances“</a>

# Sonstiges
<a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/loesungshinweise.pdf" target="_blank">Lösungshinweise zu den Aufgaben im Buch</a>

Die Rohdaten und Skripts zu den Korpusanalysen sowie die Ergebnisse der experimentellen Studie zum am-Progressiv finden Sie <a href="<a href="https://github.com/hartmast/sprachgeschichte/tree/master/korpusanalysen" target="_blank">hier</a>.

Eine Liste mit Fehlern, die es in die Druckversion geschafft haben, finden Sie <a href="https://hartmast.github.io/sprachgeschichte/begleitmaterial/Errata.pdf" target="_blank">hier</a>.